name: Terraform

on:
   push:
      branches: 
        - master
      paths-ignore:
        - '.github/**'

jobs:
   terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1.0.0
       
    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.4.6
      env:
         ARM_CLIENT_ID: ${{ secrets.AZ_DEV_CLIENT_ID}}
         ARM_CLIENT_SECRET: ${{ secrets.AZ_DEV_CLIENT_SECRET}} 
         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
         ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions/validate@v0.4.6
 
    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.6
      env:   
         ARM_CLIENT_ID: ${{ secrets.AZ_DEV_CLIENT_ID}}
         ARM_CLIENT_SECRET: ${{ secrets.AZ_DEV_CLIENT_SECRET}} 
         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
         ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
        
    - name: Terraform - Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.6
      env:   
         ARM_CLIENT_ID: ${{ secrets.AZ_DEV_CLIENT_ID}}
         ARM_CLIENT_SECRET: ${{ secrets.AZ_DEV_CLIENT_SECRET}} 
         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
         ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
   
